apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  revisionHistoryLimit: 5
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      imagePullSecrets:
	- name: dockerhubcred
      containers:
        - name: javawebappcontainer
          image: vkrishna8/java-web-app-docker-private:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  selector:
    app: javawebapp
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javaweabppingressrule
spec:
  ingressClassName: nginx
  rules:
  - host: javawebapp.tech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: javawebappsvc
            port:
              number: 80
